version: "3.9"

# Services
services:
    
    user_service:
        build: ./userservice
        volumes:
            - ./userservice:/app
        working_dir: /app
        ports:
            - 4000:4000

    # MySQL Service
    user_service_db:
        image: mysql:8
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=user_service
        volumes:
            - mysqldata:/var/lib/mysql:delegated

    # MySQL Service
    user_service_test_db:
        image: mysql:8
        ports:
            - 3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=user_service_test
        volumes:
            - mysqltestdata:/var/lib/mysql:delegated

    subscription_service:
        build: ./subscriptionservice
        volumes:
            - ./subscriptionservice:/app
        working_dir: /app
        ports:
            - 4001:4001

    # MySQL Service
    subscription_service_db:
        image: mysql:8
        ports:
            - 3308:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=subscription_service
        volumes:
            - susbscriptiondata:/var/lib/mysql:delegated

    # MySQL Service
    subscription_service_test_db:
        image: mysql:8
        ports:
            - 3309:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=subscription_service_test
        volumes:
            - subscriptiontestdata:/var/lib/mysql:delegated

    story_service:
        build: ./storyservice
        volumes:
            - ./storyservice:/app
        working_dir: /app
        ports:
            - 4002:4002

    # MongoDB Service
    story_service_db:
        image: mongo:5.0.6-focal
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: story_service
    
    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=story_service_db
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
            - ME_CONFIG_MONGODB_AUTH_USERNAME=root
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
            - ME_CONFIG_BASICAUTH_USERNAME=root
            - ME_CONFIG_BASICAUTH_PASSWORD=root
        depends_on:
            - story_service_db
        ports:
          - "8888:8081"

    # PhpMyAdmin Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5
        ports:
            - 9000:80
        environment:
            PMA_HOSTS: user_service_db, user_service_test_db, subscription_service_db, subscription_service_test_db
        volumes:
            - phpmyadmindata:/var/www/html:delegated
        depends_on:
            - user_service_db

    # Rabbitmq Service
    message_broker:
        image: rabbitmq:3.9-management
        ports:
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=root 
            - RABBITMQ_DEFAULT_PASS=root
            
# Volumes
volumes:

    mysqldata:

    mysqltestdata:

    susbscriptiondata:

    subscriptiontestdata:

    phpmyadmindata:
